#!/usr/bin/env python3
"""Generate the navigation rail from the dashboard specs, into every page.

The rail was hand-written into each of the four pages. With one country that is
merely repetitive; with four it is where mistakes live, because adding a country
means editing every page and the one you miss looks fine. The specs already
carry region, topic, title and path — they are the catalog, so they are the
source.

Structure follows the URL taxonomy, region → topic → dashboard, one disclosure
level per tier. Only the region holding the current page is open, and within it
only the topic holding it, so the rail stays about the same height whether there
is one country or six. On the landing page nothing is open at all.

The in-report contents list sits AFTER `<!-- nav:end -->` but still inside
`<nav>`, and is per-page — regenerated by the reorder script, not here. Only the
region/topic tree between the markers is rewritten. Removing that distinction
once deleted every contents list on the site.

The landing page carries no rail and no index: the map is its navigation,
and each covered region's dashboards are listed on a card shown while the
pointer is on the region (`card_html`), generated from the same specs.

Planned dashboards live in `planned.yml` at the repo root — deliberately
not in `dashboards/`, which is for specs the exporter reads. They are not specs — they
have no series and nothing to export — but they belong in the rail, because a
navigation that hides what is coming makes the site look smaller than the plan.

Usage:  python3 tools/build_nav.py [--check]
"""
from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "dashboards"
SITE = ROOT / "site"
START, END = "<!-- nav:start -->", "<!-- nav:end -->"


def slug(text: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in text).strip("-")


def catalog() -> list[dict]:
    """Every dashboard, live or planned, in the order the specs are found."""
    out = []
    # Filename order is not editorial order: the flagship dashboard should lead
    # its topic, so each spec carries an explicit nav_order.
    for p in sorted(SPECS.glob("*.yml")):
        d = yaml.safe_load(p.read_text(encoding="utf-8"))
        out.append({"region": d["region"], "topic": d["topic"],
                    "title": d["title"], "path": "/" + d["path"].strip("/") + "/",
                    "order": d.get("nav_order", 99), "planned": False,
                    "agency": d.get("agency", ""), "blurb": d.get("blurb", ""),
                    "index_title": d.get("index_title", d["title"]),
                    "headline": d.get("headline"),
                    "bundle": d["path"].replace("/", "-"),
                    "prefix": "/" + d["path"].strip("/").split("/")[0] + "/"})
    planned = ROOT / "planned.yml"
    if planned.exists():
        for d in yaml.safe_load(planned.read_text(encoding="utf-8")) or []:
            out.append({"region": d["region"], "topic": d["topic"],
                        "title": d["title"], "path": None,
                        "order": d.get("nav_order", 99), "planned": True,
                        "agency": d.get("agency", ""),
                        "blurb": d.get("blurb", "Next to be built."),
                        "bundle": None, "prefix": None})
    return sorted(out, key=lambda d: (d["order"], d["title"]))



CARD_START, CARD_END = "<!-- card:start -->", "<!-- card:end -->"


def card_html(items: list[dict]) -> str:
    """The landing page's cards: one per covered region, listing its dashboards
    by topic. A card is shown while the pointer is on its territory, so it is
    the index the page no longer carries, produced on demand from the map.

    The index this replaced went stale the day a dashboard shipped, which is
    why it was generated; the card is generated for the same reason. The
    figure on each row is NOT written here: the row carries the spec's
    `headline` (series, transform, format) as data attributes and the page
    resolves it from the bundle at load, with the engine's own `resolve` and
    `fmtFor`, so the card shows the figure the dashboard shows, from the same
    data, on the same clock.

    Paired with the map by URL prefix: the card's `data-prefix` is the href
    of the territory's link, and nothing else has to agree.
    """
    tree: dict = {}
    for it in items:
        if not it["planned"]:
            tree.setdefault(it["region"], []).append(it)
    out = []
    for region, group in sorted(tree.items()):
        pre = region_prefix(group)
        topics: dict = {}
        for it in sorted(group, key=lambda i: (i["topic"], i["order"], i["title"])):
            topics.setdefault(it["topic"], []).append(it)
        n = len(group)
        out.append('      <div class="card" id="card-%s" data-prefix="%s" role="dialog" '
                   'aria-label="%s dashboards">'
                   % (slug(region), html.escape(pre), html.escape(region)))
        out.append('        <div class="h"><a href="%s"><b>%s</b></a>'
                   '<span class="n">%d dashboard%s &middot; open &rarr;</span></div>'
                   % (html.escape(pre), html.escape(region), n, "" if n == 1 else "s"))
        for topic, its in topics.items():
            out.append('        <div class="tp">%s</div>' % html.escape(topic))
            for it in its:
                h = it.get("headline") or {}
                attrs = ' data-bundle="%s"' % html.escape(it["bundle"])
                for k in ("series", "transform", "format", "label"):
                    if h.get(k):
                        attrs += ' data-%s="%s"' % (k, html.escape(str(h[k])))
                if h.get("signed"):
                    attrs += ' data-signed="1"'
                out.append('        <a class="d" href="%s"%s><span class="nm">%s</span>'
                           '<span class="per">&hellip;</span><span class="vl">&mdash;</span></a>'
                           % (html.escape(it["path"]), attrs,
                              html.escape(it.get("index_title") or it["title"])))
        out.append('        <div class="f">&hellip;</div>')
        out.append('      </div>')
    return "\n".join(out)


def write_card(items: list[dict]) -> bool:
    """Rewrite the landing page's card block. True if it changed."""
    page = SITE / "index.html"
    s = page.read_text(encoding="utf-8")
    if CARD_START not in s or CARD_END not in s:
        print("  !! landing page has no card markers; cards not written",
              file=sys.stderr)
        return False
    a = s.index(CARD_START) + len(CARD_START)
    b = s.index(CARD_END)
    body = "\n" + card_html(items) + "\n      "
    if s[a:b] == body:
        return False
    page.write_text(s[:a] + body + s[b:], encoding="utf-8")
    return True



MAP_START, MAP_END = "<!-- map:start -->", "<!-- map:end -->"
MAP_DATA = ROOT / "tools" / "coverage-map.json"


def coverage_svg(items: list[dict]) -> str:
    """The landing page's coverage map.

    Filled and linked where a region has live dashboards; dashed outline for a
    territory we hold geometry for but have not built. The distinction comes
    from the catalogue, so building a country's first dashboard colours it in
    and nothing else has to be edited.
    """
    import json
    geo = json.loads(MAP_DATA.read_text(encoding="utf-8"))

    live: dict = {}
    for it in items:
        if it["planned"]:
            continue
        r = live.setdefault(it["region"], {"n": 0, "agencies": [],
                                            "href": it["prefix"]})
        r["n"] += 1
        ag = (it.get("agency") or "").split("\u00b7")[0].strip()
        if ag and ag not in r["agencies"]:
            r["agencies"].append(ag)

    parts = ['<svg class="map" viewBox="0 0 %d %d" role="img" '
             'aria-label="Countries covered">' % (geo["w"], geo["h"]),
             '<path class="land" d="%s"/>' % geo["base"]]

    # Every territory needs the land fill underneath, covered or not, or an
    # unbuilt country reads as a hole in the map rather than as a place.
    for name, t in geo["territories"].items():
        parts.append('<path class="land" d="%s"/>' % t["d"])

    for name, t in geo["territories"].items():
        lx, ly = t["label"]
        sx, sy = t["sub"]
        anchor = t.get("anchor", "middle")
        if name in live:
            r = live[name]
            agencies = " &middot; ".join(r["agencies"]) or "&mdash;"
            dx, dy = t.get("disc", t["label"])
            parts.append(
                '<a href="%s" aria-label="%s, %d dashboards">'
                '<title>%s &mdash; %d dashboards</title>'
                '<path class="terr" d="%s"/>'
                '<circle class="disc" cx="%s" cy="%s" r="13"/>'
                '<text class="discn" x="%s" y="%s">%d</text>'
                '<path class="lead" d="%s"/>'
                '<text class="lbl" x="%s" y="%s" text-anchor="%s">%s</text>'
                '<text class="sub" x="%s" y="%s" text-anchor="%s">%s</text>'
                '</a>'
                % (html.escape(r["href"]), html.escape(name), r["n"], html.escape(name),
                   r["n"], t["d"], dx, dy, dx, dy + 4, r["n"], t["lead"],
                   lx, ly, anchor, html.escape(name), sx, sy, anchor, agencies))
        else:
            parts.append(
                '<path class="cand" d="%s"/>'
                '<path class="lead" d="%s"/>'
                '<text class="lbl-c" x="%s" y="%s" text-anchor="%s">%s</text>'
                '<text class="sub-c" x="%s" y="%s" text-anchor="%s">%s &middot; not built</text>'
                % (t["d"], t["lead"], lx, ly, anchor, html.escape(name),
                   sx, sy, anchor, html.escape(t.get("agency", ""))))

    parts.append("</svg>")
    return "\n      ".join(parts)


def write_map(items: list[dict]) -> bool:
    """Rewrite the landing page's map block. True if it changed."""
    page = SITE / "index.html"
    s = page.read_text(encoding="utf-8")
    if MAP_START not in s or MAP_END not in s:
        print("  !! landing page has no map markers; map not written",
              file=sys.stderr)
        return False
    a = s.index(MAP_START) + len(MAP_START)
    b = s.index(MAP_END)
    body = "\n      " + coverage_svg(items) + "\n      "
    if s[a:b] == body:
        return False
    page.write_text(s[:a] + body + s[b:], encoding="utf-8")
    return True



def write_scope(items: list[dict], tree: dict) -> bool:
    """The one-line summary under the masthead stats.

    Counted, not typed: the page said "53 series" for weeks once, and this is
    the same class of sentence.
    """
    live = [i for i in items if not i["planned"]]
    n_reg = len({i["region"] for i in live})
    txt = ("%d dashboard%s &middot; %d region%s"
           % (len(live), "" if len(live) == 1 else "s",
              n_reg, "" if n_reg == 1 else "s"))
    page = SITE / "index.html"
    s = page.read_text(encoding="utf-8")
    a, b = '<div id="scope">', '</div>'
    if a not in s:
        return False
    i = s.index(a) + len(a)
    j = s.index(b, i)
    if s[i:j] == txt:
        return False
    page.write_text(s[:i] + txt + s[j:], encoding="utf-8")
    return True


# ---------------------------------------------------------- region pages ---
def region_prefix(group: list[dict]) -> str | None:
    """The URL prefix a region's dashboards share, e.g. "/us/"; None if it has
    no live dashboard. Every live dashboard in a region must sit under one
    prefix, because the region page is served at it."""
    pre = {i["prefix"] for i in group if not i["planned"]}
    if not pre:
        return None
    if len(pre) > 1:
        raise SystemExit("region %r spans several URL prefixes: %s"
                         % (group[0]["region"], sorted(pre)))
    return pre.pop()


def asset_stamp(name: str) -> str:
    """The same content hash tools/stamp_assets.py writes, so a regenerated
    region page carries the current stamp instead of losing it until the
    next stamp run (trap 5: cache-busting lives in the URL)."""
    import hashlib
    return hashlib.sha256((SITE / "assets" / name).read_bytes()).hexdigest()[:10]


def region_html(region: str, group: list[dict]) -> str:
    """One page per region: its dashboards by topic, each row carrying its own
    release's freshness, under the same rail as every dashboard.

    Generated whole from the specs, like the landing index (trap 55): a
    hand-written version would be the fourth copy of the same list and the
    first to go stale. The rail is filled in by the normal pass because the
    page carries the nav markers like any other."""
    live = [i for i in group if not i["planned"]]
    topics: dict = {}
    for it in sorted(live, key=lambda i: (i["topic"], i["order"], i["title"])):
        topics.setdefault(it["topic"], []).append(it)
    agencies = []
    for it in live:
        ag = (it.get("agency") or "").split("\u00b7")[0].strip()
        if ag and ag not in agencies:
            agencies.append(ag)
    n = len(live)
    rows = []
    for topic, its in topics.items():
        rows.append('      <h2 class="reg" id="%s"><span>%s</span>'
                    '<span class="n">%d dashboard%s</span></h2>'
                    % (slug(topic), html.escape(topic), len(its),
                       "" if len(its) == 1 else "s"))
        for it in its:
            rows.append(
                '      <a class="row" href="%s">\n'
                '        <span class="nm">%s</span>\n'
                '        <span class="agency">%s</span>\n'
                '        <span class="desc">%s</span>\n'
                '        <span class="meta" data-bundle="%s">&hellip;</span>\n'
                '      </a>' % (html.escape(it["path"]),
                                html.escape(it.get("index_title") or it["title"]),
                                html.escape(it["agency"]), html.escape(it["blurb"]),
                                html.escape(it["bundle"])))
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(region)} &mdash; BigRiceBowl Data</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=Archivo:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="/assets/brb-dash.css?v={asset_stamp("brb-dash.css")}">
</head>
<body>
<div class="app">

  <aside class="rail">
    <a class="brand" href="/">BigRiceBowl<span>Data</span></a>
    <nav aria-label="Dashboards">
  {START}
  {END}
    </nav>
  </aside>

  <main>
    <!-- GENERATED by tools/build_nav.py from dashboards/*.yml. Do not edit. -->
    <div class="crumb"><a href="/">BigRiceBowl Data</a> <b>&rsaquo;</b> {html.escape(region)}</div>
    <div class="mast">
      <h1>{html.escape(region)}</h1>
      <div class="stamp"><span><b>{n} dashboard{"" if n == 1 else "s"}</b> &middot; {len(topics)} topic{"" if len(topics) == 1 else "s"}</span><span>{html.escape(" · ".join(agencies))}</span></div>
    </div>

    <p class="lede">{html.escape(region)}: every dashboard, by topic. Each is drawn from
    one agency release and dated by it, so the rows below carry their own reference
    period and release date rather than one shared &ldquo;as of&rdquo;.</p>

    <div class="idx one" style="margin-top: 26px">
{chr(10).join(rows)}
    </div>

    <div class="src">
      <span>Sources: {html.escape(", ".join(agencies))} &mdash; via FRED and ALFRED where they carry vintages, and the agencies&rsquo; own APIs where they do not</span>
    </div>
  </main>
</div>

<script>
document.querySelectorAll(".rail .topic, .rail .region").forEach(b => b.addEventListener("click", () => {{
  const open = b.getAttribute("aria-expanded") === "true";
  b.setAttribute("aria-expanded", String(!open));
  document.getElementById(b.getAttribute("aria-controls")).hidden = open;
}}));

const MN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const MFULL = ["January","February","March","April","May","June","July",
               "August","September","October","November","December"];
const fmtDate = iso => {{ const d = new Date(iso.length === 10 ? iso + "T00:00:00Z" : iso);
  return `${{d.getUTCDate()}} ${{MN[d.getUTCMonth()]}} ${{d.getUTCFullYear()}}`; }};

// The same freshness read as the landing page: each row from its own bundle,
// because the releases run on different clocks.
document.querySelectorAll(".meta[data-bundle]").forEach(async el => {{
  try {{
    const r = await fetch(`/data/v1/dashboards/${{el.dataset.bundle}}.json`,
                          {{ credentials: "same-origin", cache: "no-cache" }});
    if (!r.ok) throw new Error(r.status);
    const b = await r.json();
    const rel = b.releases[b.release];
    const rp = rel.ref_period.split("-");
    const period = rel.cadence === "weekly"
      ? `week to ${{fmtDate(rel.ref_period)}}`
      : rel.cadence === "quarterly"
      ? `${{rp[0]}} Q${{Math.ceil(+rp[1] / 3)}}`
      : `${{MFULL[+rp[1] - 1]}} ${{rp[0]}}`;
    const days = Math.floor((Date.now() - new Date(rel.released_at)) / 86400000);
    el.innerHTML = `<b>${{period}}</b><br>released ${{fmtDate(rel.released_at)}}` +
      (rel.next_at ? `<br>next ${{fmtDate(rel.next_at)}}` : "") +
      (days > 45 ? `<br><span class="stale">${{days}} days old</span>` : "");
  }} catch (e) {{
    el.innerHTML = `<span class="stale">data unavailable</span>`;
  }}
}});
</script>
</body>
</html>
"""


def write_region_pages(items: list[dict]) -> list[str]:
    """Write site/<prefix>/index.html for every region with a live dashboard.
    Returns the paths that changed."""
    tree: dict = {}
    for it in items:
        tree.setdefault(it["region"], []).append(it)
    changed = []
    for region, group in tree.items():
        pre = region_prefix(group)
        if not pre:
            continue
        page = SITE / pre.strip("/") / "index.html"
        page.parent.mkdir(parents=True, exist_ok=True)
        new = region_html(region, group)
        if page.exists():
            old = page.read_text(encoding="utf-8")
            # The rail between the markers is the rail pass's business;
            # compare everything else, so an unchanged page is not rewritten.
            strip = lambda t: t.split(START, 1)[0] + t.split(END, 1)[-1] \
                if START in t and END in t else t
            if strip(old) == strip(new):
                continue
            # Keep the rail already in place; the rail pass rewrites it anyway.
            if START in old and END in old:
                rail = old[old.index(START): old.index(END) + len(END)]
                new = new.replace(START + "\n  " + END, rail, 1)
        page.write_text(new, encoding="utf-8")
        changed.append(str(page.relative_to(ROOT)))
    return changed


def grouped(items: list[dict]) -> dict:
    """region -> topic -> [dashboards], deterministically ordered.

    A region or topic holding something built comes before one that is only
    planned, and within each group they sort by name. Derived from the data, so
    adding a country never moves the others and no list needs maintaining.
    """
    tree: dict = {}
    for it in items:
        tree.setdefault(it["region"], {}).setdefault(it["topic"], []).append(it)

    def rank(group: dict) -> tuple:
        # 0 if anything under here is live, 1 if it is all still planned.
        live = any(not i["planned"] for sub in group.values() for i in sub) \
            if isinstance(next(iter(group.values()), None), list) else False
        return (0 if live else 1,)

    def topic_rank(entries: list) -> tuple:
        return (0 if any(not i["planned"] for i in entries) else 1,)

    out: dict = {}
    for region in sorted(tree, key=lambda r: rank(tree[r]) + (r,)):
        topics = tree[region]
        out[region] = {t: topics[t]
                       for t in sorted(topics, key=lambda t: topic_rank(topics[t]) + (t,))}
    return out


def render(tree: dict, current: str | None) -> str:
    """The rail for one page. `current` is that page's URL path, or None."""
    # Which branches to open: only the one holding this page. On the landing
    # page nothing is open, because that page is already the index — every
    # dashboard is listed in the main column with its release and freshness, so
    # an expanded rail beside it repeats itself, and picking one region to open
    # only looks more arbitrary as countries are added.
    open_region = open_topic = None
    for region, topics in tree.items():
        for topic, items in topics.items():
            if current and any(i["path"] == current for i in items):
                open_region, open_topic = region, topic
    # A region's own page (/us/) matches no dashboard, so open the region and
    # leave every topic closed: the page itself is the list.
    if current and open_region is None:
        for region, topics in tree.items():
            if any(i["prefix"] == current for its in topics.values() for i in its):
                open_region = region

    lines = [START]
    for region, topics in tree.items():
        r_open = region == open_region
        rid = f"r-{slug(region)}"
        lines.append(
            f'  <button class="region" type="button" aria-expanded="{str(r_open).lower()}"'
            f' aria-controls="{rid}"><span class="mk"></span>{html.escape(region)}</button>')
        lines.append(f'  <div class="grp" id="{rid}"{"" if r_open else " hidden"}>')
        for topic, items in topics.items():
            t_open = r_open and topic == open_topic
            tid = f"g-{slug(region)}-{slug(topic)}"
            lines.append(
                f'    <button class="topic" type="button" aria-expanded="{str(t_open).lower()}"'
                f' aria-controls="{tid}"><span class="mk"></span>{html.escape(topic)}</button>')
            lines.append(f'    <div class="grp" id="{tid}"{"" if t_open else " hidden"}>')
            for it in items:
                name = html.escape(it["title"])
                if it["planned"]:
                    lines.append(f'      <a href="#" class="soon">{name}</a>')
                else:
                    cur = ' aria-current="page"' if it["path"] == current else ""
                    lines.append(f'      <a href="{it["path"]}"{cur}>{name}</a>')
            lines.append("    </div>")
        lines.append("  </div>")
    lines.append("  " + END)
    return "\n".join(lines)


def page_path(f: Path) -> str | None:
    """The URL a page is served at; None for the landing page."""
    rel = f.parent.relative_to(SITE).as_posix()
    return None if rel == "." else "/" + rel + "/"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing")
    args = ap.parse_args()

    items = catalog()
    tree = grouped(items)
    n_regions = len(tree)
    n_live = sum(1 for r in tree.values() for t in r.values() for i in t if not i["planned"])
    print(f"{n_regions} region(s), {n_live} live dashboard(s)")
    if not args.check and write_card(items):
        print('  updated  site/index.html (region cards)')
    if not args.check and write_map(items):
        print('  updated  site/index.html (coverage map)')
    if not args.check and write_scope(items, tree):
        print('  updated  site/index.html (scope line)')
    if not args.check:
        for rel in write_region_pages(items):
            print(f'  updated  {rel} (region page)')

    changed = missing = 0
    for f in sorted(SITE.rglob("index.html")):
        text = f.read_text(encoding="utf-8")
        if page_path(f) is None:
            # The landing page has no rail by design -- the map is its
            # navigation -- so it is not missing markers, it has no need of
            # them. Anything else without markers is still a fault.
            print(f"  skipped  {f.relative_to(ROOT)} (no rail on the landing page)")
            continue
        if START not in text or END not in text:
            print(f"  !! no nav markers in {f.relative_to(ROOT)}", file=sys.stderr)
            missing += 1
            continue
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        new = head + render(tree, page_path(f)) + tail
        if new != text:
            changed += 1
            print(f"  updated  {f.relative_to(ROOT)}")
            if not args.check:
                f.write_text(new, encoding="utf-8")
        else:
            print(f"  same     {f.relative_to(ROOT)}")

    if missing:
        print(f"\n{missing} page(s) have no nav markers — add "
              f"{START} / {END} inside the rail", file=sys.stderr)
        return 1
    print(f"\n{changed} page(s) {'would change' if args.check else 'rewritten'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
